name: Movie-Reviews CI/CD

on:
  push:
    paths:
      - "./**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.9"
      - name: Install dependencies
        run: |
          python -m pip Install --upgrade pip
          pip install --no-cache-dir -r ./requirements.txt
      - name: Test with pytest
        run: |
          pytest
